import type {
  Tenant,
  Engagement,
  EvidenceItem,
  IntelligenceSignal,
  Dataset,
  KnowledgeArtifact,
  QAReview,
  ProductApp,
} from "./types";

// All data below is fictional demonstration data for Release 0.1.
// No real client, patient, or organisational data is represented.

export const tenants: Tenant[] = [
  {
    id: "t-001",
    code: "ZIPROH",
    name: "ZIPROH Assurance",
    sector: "Health & Social Care Compliance",
    status: "active",
    region: "UK",
    provisionedOn: "2026-01-14",
    modulesEnabled: 7,
    activeEngagements: 4,
    healthScore: 92,
  },
  {
    id: "t-002",
    code: "KUNCOACH",
    name: "KunCoach Advisory",
    sector: "Executive Coaching",
    status: "provisioning",
    region: "UK / GCC",
    provisionedOn: "2026-06-30",
    modulesEnabled: 2,
    activeEngagements: 0,
    healthScore: 41,
  },
  {
    id: "t-003",
    code: "KUNTOWN",
    name: "Kuntown Living",
    sector: "Property & Lifestyle",
    status: "suspended",
    region: "Africa",
    provisionedOn: "2026-04-02",
    modulesEnabled: 1,
    activeEngagements: 0,
    healthScore: 12,
  },
];

export const engagements: Engagement[] = [
  {
    id: "e-1001",
    tenantId: "t-001",
    name: "Regulation 12 & 17 Assurance Response",
    client: "Fictional Care Group Ltd",
    lead: "A. Marechera",
    status: "evidence_review",
    domain: "CQC Compliance",
    opened: "2026-05-04",
    dueDate: "2026-07-18",
    evidenceCount: 38,
    riskLevel: "high",
  },
  {
    id: "e-1002",
    tenantId: "t-001",
    name: "Workforce Compliance Audit",
    client: "Fictional Supreme Homecare",
    lead: "T. Nyathi",
    status: "active",
    domain: "Workforce Assurance",
    opened: "2026-06-01",
    dueDate: "2026-08-02",
    evidenceCount: 21,
    riskLevel: "medium",
  },
  {
    id: "e-1003",
    tenantId: "t-001",
    name: "Board Assurance Framework Refresh",
    client: "Fictional Cedarbrook Trust",
    lead: "E. Kunonga",
    status: "qa",
    domain: "Governance",
    opened: "2026-04-11",
    dueDate: "2026-07-10",
    evidenceCount: 54,
    riskLevel: "low",
  },
  {
    id: "e-1004",
    tenantId: "t-001",
    name: "CQC Readiness Diagnostic",
    client: "Fictional Northgate Care",
    lead: "S. Chikafu",
    status: "scoping",
    domain: "CQC Compliance",
    opened: "2026-06-28",
    dueDate: "2026-09-01",
    evidenceCount: 3,
    riskLevel: "medium",
  },
];

export const evidence: EvidenceItem[] = [
  {
    id: "ev-01",
    engagementId: "e-1001",
    title: "Medication Management Policy v4",
    type: "policy",
    source: "SharePoint — Fictional Care Group",
    ingested: "2026-06-29",
    classification: "confidential",
    sizeKb: 812,
  },
  {
    id: "ev-02",
    engagementId: "e-1001",
    title: "Staff Rota — June 2026",
    type: "dataset",
    source: "Rota System Export",
    ingested: "2026-06-30",
    classification: "internal",
    sizeKb: 214,
  },
  {
    id: "ev-03",
    engagementId: "e-1001",
    title: "Registered Manager Interview Transcript",
    type: "interview",
    source: "Field Assessment",
    ingested: "2026-07-01",
    classification: "restricted",
    sizeKb: 96,
  },
  {
    id: "ev-04",
    engagementId: "e-1002",
    title: "DBS Renewal Tracker",
    type: "dataset",
    source: "HR Platform Export",
    ingested: "2026-06-25",
    classification: "confidential",
    sizeKb: 145,
  },
  {
    id: "ev-05",
    engagementId: "e-1003",
    title: "Prior Inspection Report — Fictional Cedarbrook",
    type: "audit",
    source: "CQC Public Register (fictional)",
    ingested: "2026-05-20",
    classification: "internal",
    sizeKb: 1024,
  },
];

export const signals: IntelligenceSignal[] = [
  {
    id: "sig-01",
    title: "Rising medication error rate across three homecare tenants",
    category: "risk",
    tenant: "ZIPROH",
    confidence: 0.87,
    summary:
      "Pattern detected across evidence intake: medication administration record gaps increased 23% quarter-on-quarter across sampled engagements.",
    detected: "2026-07-02",
    severity: "elevated",
  },
  {
    id: "sig-02",
    title: "Board Assurance Framework template reuse opportunity",
    category: "opportunity",
    tenant: "ZIPROH",
    confidence: 0.74,
    summary:
      "The Cedarbrook BAF structure matches 5 other open engagements closely enough to templatise into ZAI-06.",
    detected: "2026-06-30",
    severity: "watch",
  },
  {
    id: "sig-03",
    title: "Regulation 17 evidence threshold reached",
    category: "compliance",
    tenant: "ZIPROH",
    confidence: 0.95,
    summary:
      "Fictional Care Group Ltd engagement has sufficient governance evidence volume to progress to QA stage.",
    detected: "2026-07-03",
    severity: "info",
  },
  {
    id: "sig-04",
    title: "Coaching intake demand outpacing KunCoach provisioning",
    category: "trend",
    tenant: "KUNCOACH",
    confidence: 0.62,
    summary:
      "Simulated interest signals suggest tenant should be prioritised for full provisioning ahead of schedule.",
    detected: "2026-06-28",
    severity: "watch",
  },
];

export const datasets: Dataset[] = [
  {
    id: "ds-01",
    name: "CQC Regulation Breach Patterns (fictional)",
    domain: "Compliance",
    rows: 48210,
    refreshCadence: "Daily",
    lastSync: "2026-07-04 06:12",
    quality: 96,
    sensitivity: "internal",
  },
  {
    id: "ds-02",
    name: "Workforce Compliance Master",
    domain: "Workforce",
    rows: 12894,
    refreshCadence: "Hourly",
    lastSync: "2026-07-04 09:40",
    quality: 91,
    sensitivity: "confidential",
  },
  {
    id: "ds-03",
    name: "Engagement Evidence Index",
    domain: "Engagements",
    rows: 3021,
    refreshCadence: "Real-time",
    lastSync: "2026-07-04 09:58",
    quality: 99,
    sensitivity: "restricted",
  },
  {
    id: "ds-04",
    name: "Tenant Health Telemetry",
    domain: "Platform Operations",
    rows: 640,
    refreshCadence: "Real-time",
    lastSync: "2026-07-04 09:59",
    quality: 100,
    sensitivity: "internal",
  },
];

export const knowledgeArtifacts: KnowledgeArtifact[] = [
  {
    id: "ka-01",
    title: "PETAL Quality Framework",
    type: "framework",
    domain: "CQC Compliance",
    version: "2.1",
    updated: "2026-05-19",
    usageCount: 14,
  },
  {
    id: "ka-02",
    title: "Board Assurance Framework Template",
    type: "template",
    domain: "Governance",
    version: "3.0",
    updated: "2026-06-30",
    usageCount: 9,
  },
  {
    id: "ka-03",
    title: "Regulation 12/17 Response Playbook",
    type: "playbook",
    domain: "CQC Compliance",
    version: "1.4",
    updated: "2026-06-15",
    usageCount: 6,
  },
  {
    id: "ka-04",
    title: "Assurance Domain Design Standard",
    type: "standard",
    domain: "Platform Governance",
    version: "2.0",
    updated: "2026-04-28",
    usageCount: 22,
  },
  {
    id: "ka-05",
    title: "Cedarbrook BAF Precedent (fictional)",
    type: "precedent",
    domain: "Governance",
    version: "1.0",
    updated: "2026-06-30",
    usageCount: 3,
  },
];

export const qaReviews: QAReview[] = [
  {
    id: "qa-01",
    subject: "Board Assurance Framework Refresh — Draft v3",
    engagementId: "e-1003",
    reviewer: "E. Kunonga",
    status: "in_review",
    submitted: "2026-07-02",
    standard: "ZAI-06 Governance Standard",
    score: null,
  },
  {
    id: "qa-02",
    subject: "Regulation 12 Response Pack — Draft v1",
    engagementId: "e-1001",
    reviewer: "A. Marechera",
    status: "flagged",
    submitted: "2026-06-29",
    standard: "ZAI-01 CQC Standard",
    score: 62,
  },
  {
    id: "qa-03",
    subject: "Workforce Audit Evidence Bundle",
    engagementId: "e-1002",
    reviewer: "T. Nyathi",
    status: "passed",
    submitted: "2026-06-20",
    standard: "ZAI-03 Workforce Standard",
    score: 94,
  },
  {
    id: "qa-04",
    subject: "CQC Readiness Diagnostic Scope Note",
    engagementId: "e-1004",
    reviewer: "S. Chikafu",
    status: "pending",
    submitted: "2026-07-03",
    standard: "ZAI-01 CQC Standard",
    score: null,
  },
];

export const productApps: ProductApp[] = [
  {
    id: "app-01",
    code: "ZAI-01",
    name: "CQC Readiness & Response",
    domain: "Compliance",
    description:
      "Regulation-mapped assurance instrument for inspection readiness and formal response drafting.",
    tenantsUsing: 1,
    status: "ga",
  },
  {
    id: "app-02",
    code: "ZAI-02",
    name: "Safeguarding Assurance",
    domain: "Compliance",
    description: "Safeguarding evidence capture, escalation tracking, and audit trail.",
    tenantsUsing: 1,
    status: "ga",
  },
  {
    id: "app-03",
    code: "ZAI-03",
    name: "Workforce Compliance",
    domain: "Workforce",
    description: "DBS, training, and supervision compliance tracking with expiry alerts.",
    tenantsUsing: 1,
    status: "ga",
  },
  {
    id: "app-04",
    code: "ZAI-04",
    name: "Medicines Management",
    domain: "Clinical Governance",
    description: "MAR audit sampling and medication incident pattern detection.",
    tenantsUsing: 1,
    status: "ga",
  },
  {
    id: "app-05",
    code: "ZAI-05",
    name: "Quality & Outcomes",
    domain: "Clinical Governance",
    description: "Person-centred outcome tracking aligned to the PETAL framework.",
    tenantsUsing: 1,
    status: "beta",
  },
  {
    id: "app-06",
    code: "ZAI-06",
    name: "Board Assurance Framework",
    domain: "Governance",
    description: "Executive-level risk and assurance mapping for board reporting.",
    tenantsUsing: 1,
    status: "ga",
  },
  {
    id: "app-07",
    code: "ZAI-07",
    name: "Complaints & Incidents",
    domain: "Governance",
    description: "Incident logging with root cause tagging and regulator notification tracking.",
    tenantsUsing: 1,
    status: "beta",
  },
  {
    id: "app-08",
    code: "ZAI-00",
    name: "Master Workbench",
    domain: "Platform Governance",
    description: "Cross-domain executive dashboard consolidating all ZAI instruments.",
    tenantsUsing: 1,
    status: "ga",
  },
  {
    id: "app-09",
    code: "KUN-C1",
    name: "Coaching Intake & Tracts",
    domain: "Executive Coaching",
    description: "Five-tract coaching intake, session tracking, and progress reporting.",
    tenantsUsing: 0,
    status: "planned",
  },
];

export function getTenantByCode(code: string): Tenant | undefined {
  return tenants.find((t) => t.code.toLowerCase() === code.toLowerCase());
}

export function getEngagementsForTenant(tenantId: string): Engagement[] {
  return engagements.filter((e) => e.tenantId === tenantId);
}

export function getEvidenceForEngagement(engagementId: string): EvidenceItem[] {
  return evidence.filter((ev) => ev.engagementId === engagementId);
}
